// Generated by CoffeeScript 1.7.1

/**
测试计算图表坐标轴刻度生成算法
 要求如下：
 指定刻度密度，生成的刻度数要靠近它
 刻度需是固定间隔的、可延伸的（即需要包括0）、易识别的（无小数或只能是2.5倍，十进制参考）
*
 */

(function() {
  var getTicks, multiples;

  multiples = [1, 2, 5, 10];

  getTicks = function(start, end, num) {
    var aproxiateRange, aproxiateStep, aproxiateStepExponent, expandRate, lastPos, minDiff, pos, range, rangeMax, rangeMin, step, steps, ticks;
    expandRate = 0;
    range = Math.abs(end - start);
    aproxiateRange = range * (1 + expandRate * 2);
    aproxiateStep = aproxiateRange / num;
    aproxiateStepExponent = Math.floor(Math.log(aproxiateStep) / Math.log(10));
    steps = multiples.map(function(i) {
      return i * Math.pow(10, aproxiateStepExponent);
    });
    step = 0;
    minDiff = Number.MAX_VALUE;
    steps.forEach(function(s) {
      var diff;
      diff = Math.abs(aproxiateStep - s);
      if (diff < minDiff) {
        minDiff = diff;
        return step = s;
      }
    });
    rangeMin = parseFloat(Math.floor(start / step) * step);
    rangeMax = parseFloat(Math.ceil(end / step) * step);
    ticks = [];
    pos = rangeMin;
    while (pos <= rangeMax) {
      ticks.push(pos);
      pos = parseFloat(pos + step);
      if (pos === lastPos) {
        break;
      }
      lastPos = pos;
    }
    return ticks;
  };

  exports.getTicks = getTicks;

}).call(this);
